baseURL = 'mukundagg.github.io/blog'
languageCode = 'en-us'
title = "Mukund's Blog"
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "The ML Blog"
showFooter = true
footerContent = "&copy; Mukund Aggarwal. All rights reserved. Work licensed under CC BY-NC-SA."
favicon = "favicon.png"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I'm a SWE. Re-engineering blueprints and working on engaging ideas 
excites me. This blog is my journal, essaying sketches focused on, *but not limited* to, 
Reinforcement Learning, Bayesian Learning, and Probabilistic Numerics.
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/mukund-aggarwal/"

[[params.social]]
name = "github"
url = "https://github.com/mukundagg"

# Main menu pages
[[params.menu]]
name = "home"
url = "/blog/"

[[params.menu]]
name = "posts"
url = "/blog/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"